// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeDc3pkzijhoJyTgWCFtW5U9YE1jSXgeE',
    appId: '1:152744793356:web:73c24220a6098e2741e529',
    messagingSenderId: '152744793356',
    projectId: 'todo-mn',
    authDomain: 'todo-mn.firebaseapp.com',
    storageBucket: 'todo-mn.appspot.com',
    measurementId: 'G-WPD7VHEXNK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLgmd5zt_vikA0D_4T1LLid_CqMTBf9ps',
    appId: '1:152744793356:android:07d2ece51319ddb341e529',
    messagingSenderId: '152744793356',
    projectId: 'todo-mn',
    storageBucket: 'todo-mn.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVpFviXyMuNh2nO2YeEDz0N-mcmfPkhhA',
    appId: '1:152744793356:ios:75d5dff93f2121d641e529',
    messagingSenderId: '152744793356',
    projectId: 'todo-mn',
    storageBucket: 'todo-mn.appspot.com',
    iosClientId: '152744793356-k8ecb2pje89nomhdjndj1cp74vgfrm7s.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoMn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVpFviXyMuNh2nO2YeEDz0N-mcmfPkhhA',
    appId: '1:152744793356:ios:75d5dff93f2121d641e529',
    messagingSenderId: '152744793356',
    projectId: 'todo-mn',
    storageBucket: 'todo-mn.appspot.com',
    iosClientId: '152744793356-k8ecb2pje89nomhdjndj1cp74vgfrm7s.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoMn',
  );
}
